version: "3.9"

services:
  db:
    image: postgres:15
    container_name: fastapi-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/app_db
    working_dir: /code
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
      

volumes:
  postgres_data:


