name: Deploy via Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Установить Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Создать SSH-ключ
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 194.58.126.19 >> ~/.ssh/known_hosts

      - name: Debug ssh dir
        run: |
         mkdir -p ~/.ssh
         ls -la ~/.ssh
         cat ~/.ssh/id_rsa | head -n 5

      - name: Запустить Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini playbook.yml --private-key ~/.ssh/id_rsa
